### ISSUE TITLE
AttributeError: Can't pickle local object 'checkpoint.begin_background.<locals>.bg_target'

### ISSUE THREAD

**Issue by DirtyLI** [thstkdgus35/EDSR-PyTorch#105]
HI
I will ask you a new question.
When i tried to use this code to  test my own images, one error happened:
  matplotlib.use('Agg')
Making model...
Download the model

Evaluation:
Traceback (most recent call last):

  File "<ipython-input-2-51edf07202c4>", line 1, in <module>
    runfile('F:/代码/EDSR-PyTorch-master/src/main.py', args='--data_test Demo --scale 4 --pre_train download --test_only --save_results', wdir='F:/代码/EDSR-PyTorch-master/src')

  File "F:\anaconda\conda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "F:\anaconda\conda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "F:/代码/EDSR-PyTorch-master/src/main.py", line 24, in <module>
    while not t.terminate():

  File "F:\代码\EDSR-PyTorch-master\src\trainer.py", line 139, in terminate
    self.test()

  File "F:\代码\EDSR-PyTorch-master\src\trainer.py", line 83, in test
    if self.args.save_results: self.ckp.begin_background()

  File "F:\代码\EDSR-PyTorch-master\src\utility.py", line 141, in begin_background
    for p in self.process: p.start()

  File "F:\anaconda\conda\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)

  File "F:\anaconda\conda\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "F:\anaconda\conda\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)

  File "F:\anaconda\conda\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)

  File "F:\anaconda\conda\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)

AttributeError: Can't pickle local object 'checkpoint.begin_background.<locals>.bg_target'

**Comment by thstkdgus35** [comment]
Hi.

It seems there are some conflicts between ``multiprocessing`` and your system. Remove [this](https://github.com/thstkdgus35/EDSR-PyTorch/blob/9a9d7d74a5a7e010e34bc9784f0e83d6055d85e7/src/trainer.py#L83) and [these](https://github.com/thstkdgus35/EDSR-PyTorch/blob/9a9d7d74a5a7e010e34bc9784f0e83d6055d85e7/src/trainer.py#L117-L118) lines to disable multiprocessing.

Thank you

**Comment by Drakael** [comment]
Hello,
I had the same error and worked it around by taking out the bg_target method inside begin_background() and making it a static method of the checkpoint class
