### ISSUE TITLE
EOFError 

### ISSUE THREAD

**Issue by tangjiuqi097** [thstkdgus35/EDSR-PyTorch#119]
when I train the EDSR baseline model (x2) with default args, it raise EOFError.

I run the following command
     python main.py --model EDSR --scale 2 --patch_size 96 --save edsr_baseline_x2 --reset  

and the message is 
(py36torch10) tangjiuqi097@tangjiuqi097-computer:~/code/EDSR-PyTorch-master/src$ python main.py --model EDSR --scale 2 --patch_size 96 --save edsr_baseline_x2 --reset
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_HR/0001.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_HR/0002.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_HR/0003.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_HR/0004.pt
... 
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_HR/0798.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_HR/0799.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_HR/0800.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0001x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0002x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0003x2.pt
...
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0757x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0758x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0759x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0760x2.pt
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    loader = data.Data(args)
  File "/home/tangjiuqi097/code/EDSR-PyTorch-master/src/data/__init__.py", line 23, in __init__
    datasets.append(getattr(m, module_name)(args, name=d))
  File "/home/tangjiuqi097/code/EDSR-PyTorch-master/src/data/div2k.py", line 17, in __init__
    args, name=name, train=train, benchmark=benchmark
  File "/home/tangjiuqi097/code/EDSR-PyTorch-master/src/data/srdata.py", line 58, in __init__
    self._check_and_load(args.ext, l, b, verbose=True) 
  File "/home/tangjiuqi097/code/EDSR-PyTorch-master/src/data/srdata.py", line 96, in _check_and_load
    pickle.dump(imageio.imread(img), _f)
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/imageio/core/functions.py", line 221, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/imageio/core/functions.py", line 143, in get_reader
    return format.get_reader(request)
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/imageio/core/format.py", line 174, in get_reader
    return self.Reader(self, request)
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/imageio/core/format.py", line 224, in __init__
    self._open(**self.request.kwargs.copy())
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/imageio/plugins/pillow.py", line 276, in _open
    return PillowFormat.Reader._open(self, pilmode=pilmode, as_gray=as_gray)
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/imageio/plugins/pillow.py", line 125, in _open
    pil_try_read(self._im)
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/imageio/plugins/pillow.py", line 501, in pil_try_read
    im.getdata()[0]
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/PIL/Image.py", line 1270, in getdata
    self.load()
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/PIL/ImageFile.py", line 250, in load
    self.load_end()
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/PIL/PngImagePlugin.py", line 677, in load_end
    self.png.call(cid, pos, length)
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/PIL/PngImagePlugin.py", line 140, in call
    return getattr(self, "chunk_" + cid.decode('ascii'))(pos, length)
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/PIL/PngImagePlugin.py", line 356, in chunk_IDAT
    raise EOFError
EOFError

when I run 
  python main.py --model EDSR --scale 2 --patch_size 96 --save edsr_baseline_x2 --reset  --ext img
it got similar error

(py36torch10) tangjiuqi097@tangjiuqi097-computer:~/code/EDSR-PyTorch-master/src$ python main.py --model EDSR --scale 2 --patch_size 96 --save edsr_baseline_x2 --reset  --ext img
Making model...
Preparing loss function:
1.000 * L1
[Epoch 1]	Learning rate: 1.00e-4
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    t.train()
  File "/home/tangjiuqi097/code/EDSR-PyTorch-master/src/trainer.py", line 41, in train
    for batch, (lr, hr, _, idx_scale) in enumerate(self.loader_train):
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
EOFError: Traceback (most recent call last):
  File "/home/tangjiuqi097/code/EDSR-PyTorch-master/src/dataloader.py", line 65, in _ms_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/tangjiuqi097/code/EDSR-PyTorch-master/src/dataloader.py", line 65, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 81, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/tangjiuqi097/code/EDSR-PyTorch-master/src/data/srdata.py", line 99, in __getitem__
    lr, hr, filename = self._load_file(idx)
  File "/home/tangjiuqi097/code/EDSR-PyTorch-master/src/data/srdata.py", line 126, in _load_file
    lr = imageio.imread(f_lr)
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/imageio/core/functions.py", line 221, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/imageio/core/functions.py", line 143, in get_reader
    return format.get_reader(request)
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/imageio/core/format.py", line 174, in get_reader
    return self.Reader(self, request)
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/imageio/core/format.py", line 224, in __init__
    self._open(**self.request.kwargs.copy())
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/imageio/plugins/pillow.py", line 276, in _open
    return PillowFormat.Reader._open(self, pilmode=pilmode, as_gray=as_gray)
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/imageio/plugins/pillow.py", line 125, in _open
    pil_try_read(self._im)
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/imageio/plugins/pillow.py", line 501, in pil_try_read
    im.getdata()[0]
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/PIL/Image.py", line 1270, in getdata
    self.load()
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/PIL/ImageFile.py", line 250, in load
    self.load_end()
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/PIL/PngImagePlugin.py", line 677, in load_end
    self.png.call(cid, pos, length)
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/PIL/PngImagePlugin.py", line 140, in call
    return getattr(self, "chunk_" + cid.decode('ascii'))(pos, length)
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/PIL/PngImagePlugin.py", line 356, in chunk_IDAT
    raise EOFError
EOFError

**Comment by tangjiuqi097** [comment]
when I continue run the command, it get the following message

/home/tangjiuqi097/anaconda3/envs/py36torch10/bin/python /home/tangjiuqi097/code/EDSR-PyTorch-master/src/main.py --model EDSR --scale 2 --patch_size 96 --save edsr_baseline_x2 --reset
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0761x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0762x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0763x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0764x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0765x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0766x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0767x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0768x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0769x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0770x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0771x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0772x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0773x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0774x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0775x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0776x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0777x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0778x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0779x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0780x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0781x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0782x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0783x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0784x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0785x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0786x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0787x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0788x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0789x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0790x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0791x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0792x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0793x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0794x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0795x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0796x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0797x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0798x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0799x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0800x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_HR/0801.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_HR/0802.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_HR/0803.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_HR/0804.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_HR/0805.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_HR/0806.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_HR/0807.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_HR/0808.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_HR/0809.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_HR/0810.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0801x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0802x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0803x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0804x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0805x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0806x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0807x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0808x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0809x2.pt
Making a binary: ../dataset/DIV2K/bin/DIV2K_train_LR_bicubic/X2/0810x2.pt
Making model...
Preparing loss function:
1.000 * L1
[Epoch 1]	Learning rate: 1.00e-4
Traceback (most recent call last):
  File "/home/tangjiuqi097/code/EDSR-PyTorch-master/src/main.py", line 25, in <module>
    t.train()
  File "/home/tangjiuqi097/code/EDSR-PyTorch-master/src/trainer.py", line 41, in train
    for batch, (lr, hr, _, idx_scale) in enumerate(self.loader_train):
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
EOFError: Traceback (most recent call last):
  File "/home/tangjiuqi097/code/EDSR-PyTorch-master/src/dataloader.py", line 65, in _ms_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/tangjiuqi097/code/EDSR-PyTorch-master/src/dataloader.py", line 65, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/tangjiuqi097/anaconda3/envs/py36torch10/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 81, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/tangjiuqi097/code/EDSR-PyTorch-master/src/data/srdata.py", line 99, in __getitem__
    lr, hr, filename = self._load_file(idx)
  File "/home/tangjiuqi097/code/EDSR-PyTorch-master/src/data/srdata.py", line 131, in _load_file
    lr = pickle.load(_f)
EOFError: Ran out of input

**Comment by tangjiuqi097** [comment]
It is because the python environment can not open the image DIV2K_train_LR_bicubic/X2/0760x2.png. When I change another python environment, the issue is solved . But I do not know how it happened.

**Comment by IronLavender** [comment]
> It is because the python environment can not open the image DIV2K_train_LR_bicubic/X2/0760x2.png. When I change another python environment, the issue is solved . But I do not know how it happened.

Sorry, I want to know what "change another python environment" means. The codes need pytorch, so change pytorch to what? or?

**Comment by wulongjian** [comment]
Hi, I have also meet this problems, have you solve this questions ?
