### ISSUE TITLE
RuntimeError: Expected 4-dimensional input

### ISSUE THREAD

**Issue by m732367606** [thstkdgus35/EDSR-PyTorch#128]
Got an error when trying to test on DIV2K dataset, can anyone help?
```
- Making model...
- Load the model from ../models/EDSR_x2.pt
- 
- Evaluation:
-   0%|                                                    | 0/10 [00:00<?, ?it/s]
- Traceback (most recent call last):
-   File "D:/EDSR-PyTorch-master/src/main.py", line 33, in <module>
-     main()
-   File "D:/EDSR-PyTorch-master/src/main.py", line 26, in main
-     while not t.terminate():
-   File "D:\EDSR-PyTorch-master\src\trainer.py", line 139, in terminate
-     self.test()
-   File "D:\EDSR-PyTorch-master\src\trainer.py", line 89, in test
-     sr = self.model(lr, idx_scale)
-   File "D:\Anaconda3\envs\EDSR\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
-     result = self.forward(*input, **kwargs)
-   File "D:\EDSR-PyTorch-master\src\model\__init__.py", line 57, in forward
-     return forward_function(x)
-   File "D:\EDSR-PyTorch-master\src\model\__init__.py", line 135, in forward_chop
-     y = self.forward_chop(*p, shave=shave, min_size=min_size)
-   File "D:\EDSR-PyTorch-master\src\model\__init__.py", line 126, in forward_chop
-     y = P.data_parallel(self.model, *x, range(n_GPUs))
-   File "D:\Anaconda3\envs\EDSR\lib\site-packages\torch\nn\parallel\data_parallel.py", line 185, in data_parallel
-     return module(*inputs[0], **module_kwargs[0])
-   File "D:\Anaconda3\envs\EDSR\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
-     result = self.forward(*input, **kwargs)
-   File "D:\EDSR-PyTorch-master\src\model\edsr.py", line 52, in forward
-     x = self.sub_mean(x)
-   File "D:\Anaconda3\envs\EDSR\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
-     result = self.forward(*input, **kwargs)
-   File "D:\Anaconda3\envs\EDSR\lib\site-packages\torch\nn\modules\conv.py", line 320, in forward
-     self.padding, self.dilation, self.groups)
- RuntimeError: Expected 4-dimensional input for 4-dimensional weight [3, 3, 1, 1], but got 3-dimensional input of size [1, 184, 270] instead
```

The following are the commands I input:
`python main.py --dir_data . --data_test DIV2K --scale 2 --pre_train ../models/EDSR_x2.pt --test_only --data_range 801-810 --n_resblocks 32 --n_feats 256 --res_scale 0.1 --save_results --chop --patch_size 96`

**Comment by ch135** [comment]
Hello, do you solve this problem? I have the same problem when I run 

> python main.py --model EDSR --scale 2 --patch_size 96 --save edsr_baseline_x2 --reset --n_GPUs 2 --chop

>

Traceback (most recent call last):
  File "main.py", line 33, in <module>
    main()
  File "main.py", line 28, in main
    t.test()
  File "/media/wangct/E7D0AC3987855C5C/ch_git/EDSR-PyTorch/src/trainer.py", line 89, in test
    sr = self.model(lr, idx_scale)
  File "/home/wangct/.conda/envs/chenhao/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/wangct/E7D0AC3987855C5C/ch_git/EDSR-PyTorch/src/model/__init__.py", line 57, in forward
    return forward_function(x)
  File "/media/wangct/E7D0AC3987855C5C/ch_git/EDSR-PyTorch/src/model/__init__.py", line 135, in forward_chop
    y = self.forward_chop(*p, shave=shave, min_size=min_size)
  File "/media/wangct/E7D0AC3987855C5C/ch_git/EDSR-PyTorch/src/model/__init__.py", line 126, in forward_chop
    y = P.data_parallel(self.model, *x, range(n_GPUs))
  File "/home/wangct/.conda/envs/chenhao/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 188, in data_parallel
    outputs = parallel_apply(replicas, inputs, module_kwargs, used_device_ids)
  File "/home/wangct/.conda/envs/chenhao/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/wangct/.conda/envs/chenhao/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home/wangct/.conda/envs/chenhao/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/wangct/E7D0AC3987855C5C/ch_git/EDSR-PyTorch/src/model/edsr.py", line 52, in forward
    x = self.sub_mean(x)
  File "/home/wangct/.conda/envs/chenhao/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wangct/.conda/envs/chenhao/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [3, 3, 1, 1], but got 3-dimensional input of size [1, 184, 270] instead

 
Could you help me solve this problem?

**Comment by ontheway16** [comment]
@ch135 @m732367606 Count me, too.

python main.py --data_test Demo --scale 4 --pre_train download --test_only --save_results --chop

same error above.
`RuntimeError: Expected 4-dimensional input for 4-dimensional weight [3, 3, 1, 1], but got......................
`

**Comment by m732367606** [comment]
Please try the following parameters:
`--model EDSR--scale 4 --save xxxx--reset --data_train DIV2K --dir_data . --save_results --epoch 300 --data_test xxxx--chop --patch_size 96 --batch_size 16`
Please make sure that you have datasets in the src floder.

**Comment by m732367606** [comment]
It seems that there is something wrong when testing with DIV2K images. Reproducing...
