### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by ontheway16** [thstkdgus35/EDSR-PyTorch#140]
Hi, I am using unmodified version of the code and in demo.sh, after adding --chop option to the line, it gives the following error, then all cpu cores rises and keep running at 100%. What might be the problem?

```
$ sh demo.sh
Making model...
Load the model from ../experiment/model/EDSR_baseline_x4.pt

Evaluation:
  0%|                                                     | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    main()
  File "main.py", line 26, in main
    while not t.terminate():
  File "/home/gpuser/EDSR-PyTorch/src/trainer.py", line 139, in terminate
    self.test()
  File "/home/gpuser/EDSR-PyTorch/src/trainer.py", line 89, in test
    sr = self.model(lr, idx_scale)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gpuser/EDSR-PyTorch/src/model/__init__.py", line 57, in forward
    return forward_function(x)
  File "/home/gpuser/EDSR-PyTorch/src/model/__init__.py", line 135, in forward_chop
    y = self.forward_chop(*p, shave=shave, min_size=min_size)
  File "/home/gpuser/EDSR-PyTorch/src/model/__init__.py", line 135, in forward_chop
    y = self.forward_chop(*p, shave=shave, min_size=min_size)
  File "/home/gpuser/EDSR-PyTorch/src/model/__init__.py", line 135, in forward_chop
    y = self.forward_chop(*p, shave=shave, min_size=min_size)
  File "/home/gpuser/EDSR-PyTorch/src/model/__init__.py", line 109, in forward_chop
    h, w = args[0].size()[-2:]
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by ontheway16** [comment]
Above was with pytorch 1.0.1.
Tried with pytorch 1.0.0, still the same..

**Comment by ontheway16** [comment]
OK I have changed something and error is now like:

```
$ bash demo.sh 
Making model...
Download the model
Downloading: "https://cv.snu.ac.kr/research/EDSR/models/edsr_baseline_x4-6b446fab.pt" to ../models/edsr_baseline_x4-6b446fab.pt
100%|████████████████████████████████████████████████████████████████| 6081831/6081831 [00:03<00:00, 1929090.03it/s]

Evaluation:
  0%|                                                     | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    main()
  File "main.py", line 26, in main
    while not t.terminate():
  File "/home/gpuser/environments/pytorch-env/EDSR-PyTorch/src/trainer.py", line 139, in terminate
    self.test()
  File "/home/gpuser/environments/pytorch-env/EDSR-PyTorch/src/trainer.py", line 89, in test
    sr = self.model(lr, idx_scale)
  File "/home/gpuser/environments/pytorch-env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gpuser/environments/pytorch-env/EDSR-PyTorch/src/model/__init__.py", line 57, in forward
    return forward_function(x)
  File "/home/gpuser/environments/pytorch-env/EDSR-PyTorch/src/model/__init__.py", line 135, in forward_chop
    y = self.forward_chop(*p, shave=shave, min_size=min_size)
  File "/home/gpuser/environments/pytorch-env/EDSR-PyTorch/src/model/__init__.py", line 135, in forward_chop
    y = self.forward_chop(*p, shave=shave, min_size=min_size)
  File "/home/gpuser/environments/pytorch-env/EDSR-PyTorch/src/model/__init__.py", line 126, in forward_chop
    y = P.data_parallel(self.model, *x, range(n_GPUs))
  File "/home/gpuser/environments/pytorch-env/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 185, in data_parallel
    return module(*inputs[0], **module_kwargs[0])
  File "/home/gpuser/environments/pytorch-env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gpuser/environments/pytorch-env/EDSR-PyTorch/src/model/edsr.py", line 52, in forward
    x = self.sub_mean(x)
  File "/home/gpuser/environments/pytorch-env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gpuser/environments/pytorch-env/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [3, 3, 1, 1], but got 2-dimensional input of size [1, 272] instead
```

**Comment by ontheway16** [comment]
@thstkdgus35 Hello, do you have any opinions about what might be wrong above? I have installed pytorch etc with conda, and testing the code without changing anything except tested image. Using Ubuntu 16.04. It works well without --chop option, by the way. Thanks !

**Comment by thstkdgus35** [comment]
Hello,

I think there is a problem with your input image.

Make sure that it has 3 color channels (RGB), otherwise similar things can happen.

If possible, please upload your test image so that I can test it.

Thank you for reporting the bug!

**Comment by ontheway16** [comment]
Hi @thstkdgus35 ,

I just retested the install with following line:
python main.py --data_test Demo --scale 4 --pre_train download --test_only --save_results --chop

The only test image was 0826.png from DIV2K set.
 following error come out:

```
$ bash demo.sh 
Making model...
Download the model

Evaluation:
  0%|                                                     | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    main()
  File "main.py", line 26, in main
    while not t.terminate():
  File "/home/gpuser/EDSR-PyTorch-master/src/trainer.py", line 139, in terminate
    self.test()
  File "/home/gpuser/EDSR-PyTorch-master/src/trainer.py", line 89, in test
    sr = self.model(lr, idx_scale)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gpuser/EDSR-PyTorch-master/src/model/__init__.py", line 57, in forward
    return forward_function(x)
  File "/home/gpuser/EDSR-PyTorch-master/src/model/__init__.py", line 135, in forward_chop
    y = self.forward_chop(*p, shave=shave, min_size=min_size)
  File "/home/gpuser/EDSR-PyTorch-master/src/model/__init__.py", line 135, in forward_chop
    y = self.forward_chop(*p, shave=shave, min_size=min_size)
  File "/home/gpuser/EDSR-PyTorch-master/src/model/__init__.py", line 126, in forward_chop
    y = P.data_parallel(self.model, *x, range(n_GPUs))
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 185, in data_parallel
    return module(*inputs[0], **module_kwargs[0])
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gpuser/EDSR-PyTorch-master/src/model/edsr.py", line 52, in forward
    x = self.sub_mean(x)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [3, 3, 1, 1], but got 2-dimensional input of size [1, 272] instead
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
Process Process-6:
Process Process-3:
Process Process-8:
Process Process-2:
Process Process-4:
Process Process-7:
Process Process-5:
Process Process-1:
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gpuser/EDSR-PyTorch-master/src/utility.py", line 131, in bg_target
    if not queue.empty():
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/queues.py", line 120, in empty
    return not self._poll()
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gpuser/EDSR-PyTorch-master/src/utility.py", line 131, in bg_target
    if not queue.empty():
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/queues.py", line 120, in empty
    return not self._poll()
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gpuser/EDSR-PyTorch-master/src/utility.py", line 131, in bg_target
    if not queue.empty():
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/queues.py", line 120, in empty
    return not self._poll()
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/connection.py", line 914, in wait
    selector.register(obj, selectors.EVENT_READ)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gpuser/EDSR-PyTorch-master/src/utility.py", line 131, in bg_target
    if not queue.empty():
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/selectors.py", line 351, in register
    def register(self, fileobj, events, data=None):
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gpuser/EDSR-PyTorch-master/src/utility.py", line 131, in bg_target
    if not queue.empty():
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/queues.py", line 120, in empty
    return not self._poll()
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/connection.py", line 914, in wait
    selector.register(obj, selectors.EVENT_READ)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/selectors.py", line 352, in register
    key = super().register(fileobj, events, data)
KeyboardInterrupt
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/queues.py", line 120, in empty
    return not self._poll()
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/connection.py", line 927, in wait
    return ready
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/selectors.py", line 203, in __exit__
    self.close()
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/selectors.py", line 269, in close
    self._fd_to_key.clear()
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gpuser/EDSR-PyTorch-master/src/utility.py", line 131, in bg_target
    if not queue.empty():
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/queues.py", line 120, in empty
    return not self._poll()
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gpuser/EDSR-PyTorch-master/src/utility.py", line 131, in bg_target
    if not queue.empty():
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/connection.py", line 914, in wait
    selector.register(obj, selectors.EVENT_READ)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/queues.py", line 120, in empty
    return not self._poll()
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/selectors.py", line 352, in register
    key = super().register(fileobj, events, data)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/selectors.py", line 238, in register
    key = SelectorKey(fileobj, self._fileobj_lookup(fileobj), events, data)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/selectors.py", line 225, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/connection.py", line 914, in wait
    selector.register(obj, selectors.EVENT_READ)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/selectors.py", line 352, in register
    key = super().register(fileobj, events, data)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/selectors.py", line 37, in _fileobj_to_fd
    fd = int(fileobj.fileno())
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/connection.py", line 170, in fileno
    self._check_closed()
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/selectors.py", line 238, in register
    key = SelectorKey(fileobj, self._fileobj_lookup(fileobj), events, data)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/selectors.py", line 225, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
KeyboardInterrupt
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gpuser/EDSR-PyTorch-master/src/utility.py", line 131, in bg_target
    if not queue.empty():
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/queues.py", line 120, in empty
    return not self._poll()
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/multiprocessing/connection.py", line 927, in wait
    return ready
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/selectors.py", line 203, in __exit__
    self.close()
  File "/home/gpuser/miniconda3/envs/inferen/lib/python3.7/selectors.py", line 269, in close
    self._fd_to_key.clear()
KeyboardInterrupt

```
