### ISSUE TITLE
An error when training with my own dataset with scale 3

### ISSUE THREAD

**Issue by m732367606** [thstkdgus35/EDSR-PyTorch#155]
When running EDSR model with scale 3, the following error occurs, scale 2 and 4 is OK, did anyone encounter this problem?
`Traceback (most recent call last):
  File "D:/EDSR-PyTorch-master/src/main.py", line 35, in <module>
    main()
  File "D:/EDSR-PyTorch-master/src/main.py", line 29, in main
    t.train()
  File "D:\EDSR-PyTorch-master\src\trainer.py", line 41, in train
    for batch, (lr, hr, _, idx_scale) in enumerate(self.loader_train):
  File "D:\Anaconda3\envs\EDSR\lib\site-packages\torch\utils\data\dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "D:\Anaconda3\envs\EDSR\lib\site-packages\torch\utils\data\dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "D:\EDSR-PyTorch-master\src\dataloader.py", line 65, in _ms_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\Anaconda3\envs\EDSR\lib\site-packages\torch\utils\data\dataloader.py", line 232, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "D:\Anaconda3\envs\EDSR\lib\site-packages\torch\utils\data\dataloader.py", line 232, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "D:\Anaconda3\envs\EDSR\lib\site-packages\torch\utils\data\dataloader.py", line 209, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 48 and 47 in dimension 2 at c:\a\w\1\s\tmp_conda_3.6_094431\conda\conda-bld\pytorch_1550396825513\work\aten\src\th\generic/THTensorMoreMath.cpp:1307`

**Comment by Raienryu97** [comment]
Hey @m732367606 , I see that you've closed this issue. I was wondering if you found the solution to this?
I'm having a similar issue too as your error message.

**Comment by m732367606** [comment]
> Hey @m732367606 , I see that you've closed this issue. I was wondering if you've found the solution to this?
> I'm having a similar issue too as your error message.

The solution was to make training images' size are capable of being divided. For instance, use images whose size 384*384 since 384 can be divided by 2,3,4 with without any remainder.
Hope that can help you!

**Comment by sureJ0824** [comment]
hey I am meeting an question when i train my own datasets ,I didnot know where to put my HR resolution images and LR images , I am too confused . Hope your help sooooo much
