### ISSUE TITLE
ImportError: cannot import name 'ManagerWatchdog'

### ISSUE THREAD

**Issue by 666xiaohei666** [thstkdgus35/EDSR-PyTorch#158]
(EDSR) root@docker21:/data2/yanmengkai/EDSR-PyTorch/src# sh demo.sh 
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import data
  File "/data2/yanmengkai/EDSR-PyTorch/src/data/__init__.py", line 2, in <module>
    from dataloader import MSDataLoader
  File "/data2/yanmengkai/EDSR-PyTorch/src/dataloader.py", line 14, in <module>
    from torch.utils.data.dataloader import ManagerWatchdog
ImportError: cannot import name 'ManagerWatchdog'

My pytorch version is 0.4.0
Can anyone help me?thank you!

**Comment by 666xiaohei666** [comment]
Solved this problem by upgrade pytorch to 1.0.1.
Thank you!

**Comment by thstkdgus35** [comment]
Great!
