### ISSUE TITLE
Cannot import name _update_worker_pids' from 'torch._C'

### ISSUE THREAD

**Issue by aminya** [thstkdgus35/EDSR-PyTorch#162]
When I try to run the code I get this error. I use Anaconda on Windows. (I installed all the dependencies)

```
(base) C:\Windows\system32>cd C:\Users\myPC\EDSR-PyTorch-master\src

(base) C:\Users\myPC\EDSR-PyTorch-master\src>python main.py --model EDSR --scale 2 --patch_size 96 --save edsr_baseline_x2 --reset
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import data
  File "C:\Users\myPC\EDSR-PyTorch-master\src\data\__init__.py", line 2, in <module>
    from dataloader import MSDataLoader
  File "C:\Users\myPC\EDSR-PyTorch-master\src\dataloader.py", line 10, in <module>
    from torch._C import _set_worker_signal_handlers, _update_worker_pids, \
ImportError: cannot import name '_update_worker_pids' from 'torch._C' (C:\Users\myPC\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\_C.cp37-win_amd64.pyd)
```

**Comment by thstkdgus35** [comment]
Hello.

If you found the problem after updating to PyTorch 1.1.0, I fixed the problem.

Please find the most recent commit to solve the issue.

Thank you!
