### ISSUE TITLE
ImportError: cannot import name '_utils'

### ISSUE THREAD

**Issue by assafshocher** [thstkdgus35/EDSR-PyTorch#165]
Using PyTorch 1.0.0.
Python 3.6.6.

Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import data
  File "/net/mraid11/export/data/assafsho/SR/EDSR-PyTorch/src/data/__init__.py", line 2, in <module>
    from dataloader import MSDataLoader
  File "/net/mraid11/export/data/assafsho/SR/EDSR-PyTorch/src/dataloader.py", line 10, in <module>
    from torch.utils.data import _utils
ImportError: cannot import name '_utils'

Thanks in advance.

**Comment by thstkdgus35** [comment]
Hello.

Please refer to this issue! #162 

Thank you.

**Comment by thstkdgus35** [comment]
Hello.

Please refer to this issue! #162 

Thank you.
