### ISSUE TITLE
RuntimeError: Given groups=1, weight of size 3 3 1 1, expected input[1, 4, 678, 1020] to have 3 channels, but got 4 channels instead

### ISSUE THREAD

**Issue by assafshocher** [thstkdgus35/EDSR-PyTorch#166]
PyTorch 1.1, Python 3.6.6

Traceback (most recent call last):
  File "main.py", line 33, in <module>
    main()
  File "main.py", line 26, in main
    while not t.terminate():
  File "/net/mraid11/export/data/assafsho/SR/EDSR-PyTorch/src/trainer.py", line 139, in terminate
    self.test()
  File "/net/mraid11/export/data/assafsho/SR/EDSR-PyTorch/src/trainer.py", line 89, in test
    sr = self.model(lr, idx_scale)
  File "/net/mraid11/export/vision/miniconda3/envs/EDSR/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/net/mraid11/export/data/assafsho/SR/EDSR-PyTorch/src/model/__init__.py", line 57, in forward
    return forward_function(x)
  File "/net/mraid11/export/data/assafsho/SR/EDSR-PyTorch/src/model/edsr.py", line 52, in forward
    x = self.sub_mean(x)
  File "/net/mraid11/export/vision/miniconda3/envs/EDSR/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/net/mraid11/export/vision/miniconda3/envs/EDSR/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 3 3 1 1, expected input[1, 4, 678, 1020] to have 3 channels, but got 4 channels instead

Thanks in advance!

**Comment by thstkdgus35** [comment]
Hello.

It seems that you are using a png input with alpha channel.

Please add below code right above [this line](https://github.com/thstkdgus35/EDSR-PyTorch/blob/565d6feaf58616558fb01a0c65342c01a3b3a26f/src/trainer.py#L89).

```python
lr = lr[:, :3, :, :]
```

I think this can solve your problem, and I will find a way to support the PNG format better.

Thank you for reporting!
