### ISSUE TITLE
this is a stupid question

### ISSUE THREAD

**Issue by ManoaNosea** [thstkdgus35/EDSR-PyTorch#168]
I read the demo.sh file from start to finish and I still have no idea how to upscale an image :x

**Comment by thstkdgus35** [comment]
Hello.

Don't say stupid :) simply you can put your images under ``/test`` and execute [this line](https://github.com/thstkdgus35/EDSR-PyTorch/blob/565d6feaf58616558fb01a0c65342c01a3b3a26f/src/demo.sh#L32) to do super-resolution.

Thank you!

**Comment by ManoaNosea** [comment]
I did, but he says:
```
D:\Programs64\Python-3.6.5\lib\site-packages\numpy\core\__init__.py:29: UserWarning: loaded more than 1 DLL from .libs:
D:\Programs64\Python-3.6.5\lib\site-packages\numpy\.libs\libopenblas.BNVRK7633HSX7YVO2TADGR4A5KEKXJAW.gfortran-win_amd64.dll
D:\Programs64\Python-3.6.5\lib\site-packages\numpy\.libs\libopenblas.IPBC74C7KURV7CB2PKT5Z5FNR3SIBV4J.gfortran-win_amd64.dll
  stacklevel=1)
Making model...
Load the model from ..\models\EDSR_x4.pt
Traceback (most recent call last):
  File "y:\theshitt-backup\Projects\AINeuralNetSuperRes\EDSR-PyTorch-master\src\model\edsr.py", line 70, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: The expanded size of the tensor (64) must match the existing size (256) at non-singleton dimension 0.  Target sizes: [64, 3, 3, 3].  Tensor sizes: [256, 3, 3, 3]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 33, in <module>
    main()
  File "main.py", line 23, in main
    _model = model.Model(args, checkpoint)
  File "y:\theshitt-backup\Projects\AINeuralNetSuperRes\EDSR-PyTorch-master\src\model\__init__.py", line 34, in __init__
    cpu=args.cpu
  File "y:\theshitt-backup\Projects\AINeuralNetSuperRes\EDSR-PyTorch-master\src\model\__init__.py", line 103, in load
    self.model.load_state_dict(load_from, strict=False)
  File "y:\theshitt-backup\Projects\AINeuralNetSuperRes\EDSR-PyTorch-master\src\model\edsr.py", line 76, in load_state_dict
    .format(name, own_state[name].size(), param.size()))
RuntimeError: While copying the parameter named head.0.weight, whose dimensions in the model are torch.Size([64, 3, 3, 3]) and whose dimensions in the checkpoint are torch.Size([256, 3, 3, 3]).
```

**Comment by ManoaNosea** [comment]
he also says this:
```
λ python main.py --data_test Demo --scale 4 --pre_train download --test_only --save_results --cpu
D:\Programs64\Python-3.6.5\lib\site-packages\numpy\core\__init__.py:29: UserWarning: loaded more than 1 DLL from .libs:
D:\Programs64\Python-3.6.5\lib\site-packages\numpy\.libs\libopenblas.BNVRK7633HSX7YVO2TADGR4A5KEKXJAW.gfortran-win_amd64.dll
D:\Programs64\Python-3.6.5\lib\site-packages\numpy\.libs\libopenblas.IPBC74C7KURV7CB2PKT5Z5FNR3SIBV4J.gfortran-win_amd64.dll
  stacklevel=1)
Making model...
Download the model

Evaluation:
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    main()
  File "main.py", line 26, in main
    while not t.terminate():
  File "y:\theshitt-backup\Projects\AINeuralNetSuperRes\EDSR-PyTorch-master\src\trainer.py", line 139, in terminate
    self.test()
  File "y:\theshitt-backup\Projects\AINeuralNetSuperRes\EDSR-PyTorch-master\src\trainer.py", line 83, in test
    if self.args.save_results: self.ckp.begin_background()
  File "y:\theshitt-backup\Projects\AINeuralNetSuperRes\EDSR-PyTorch-master\src\utility.py", line 141, in begin_background
    for p in self.process: p.start()
  File "D:\Programs64\Python-3.6.5\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\Programs64\Python-3.6.5\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Programs64\Python-3.6.5\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Programs64\Python-3.6.5\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Programs64\Python-3.6.5\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'checkpoint.begin_background.<locals>.bg_target'
D:\Programs64\Python-3.6.5\lib\site-packages\numpy\core\__init__.py:29: UserWarning: loaded more than 1 DLL from .libs:
D:\Programs64\Python-3.6.5\lib\site-packages\numpy\.libs\libopenblas.BNVRK7633HSX7YVO2TADGR4A5KEKXJAW.gfortran-win_amd64.dll
D:\Programs64\Python-3.6.5\lib\site-packages\numpy\.libs\libopenblas.IPBC74C7KURV7CB2PKT5Z5FNR3SIBV4J.gfortran-win_amd64.dll
  stacklevel=1)

y:\theshitt-backup\Projects\AINeuralNetSuperRes\EDSR-PyTorch-master\src
λ Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Programs64\Python-3.6.5\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\Programs64\Python-3.6.5\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```
