### ISSUE TITLE
I got error while running demo.sh

### ISSUE THREAD

**Issue by gray2bgr** [thstkdgus35/EDSR-PyTorch#176]
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import data
  File "/home/youku/scripts/EDSR-PyTorch/src/data/__init__.py", line 2, in <module>
    from dataloader import MSDataLoader
  File "/home/youku/scripts/EDSR-PyTorch/src/dataloader.py", line 10, in <module>
    from torch.utils.data import _utils
ImportError: cannot import name '_utils

**Comment by donghang941114** [comment]
me too
55555

**Comment by lisiping0817** [comment]
change pytorch version

**Comment by thstkdgus35** [comment]
If you are using one of the old versions of PyTorch, check the legacy/* branch for your version, please.
