### ISSUE TITLE
importError: cannot import name '_validate_lengths'

### ISSUE THREAD

**Issue by Wuyanfang5** [thstkdgus35/EDSR-PyTorch#179]
Traceback (most recent call last):
  File "F:/Python_Project/big_training/EDSR-PyTorch/src/main.py", line 14, in <module>
    loader = data.Data(args)
  File "F:\Python_Project\big_training\EDSR-PyTorch\src\data\__init__.py", line 10, in __init__
    module_train = import_module('data.' + args.data_train.lower())
  File "F:\pycharmPro\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\Python_Project\big_training\EDSR-PyTorch\src\data\div2k.py", line 3, in <module>
    import srdata  # 将上一行改为这个
  File "F:\Python_Project\big_training\EDSR-PyTorch\src\data\srdata.py", line 5, in <module>
    import common  # 将上一行改为这一行
  File "F:\Python_Project\big_training\EDSR-PyTorch\src\data\common.py", line 4, in <module>
    import skimage.color as sc
  File "F:\pycharmPro\lib\site-packages\skimage\__init__.py", line 158, in <module>
    from .util.dtype import *
  File "F:\pycharmPro\lib\site-packages\skimage\util\__init__.py", line 7, in <module>
    from .arraycrop import crop
  File "F:\pycharmPro\lib\site-packages\skimage\util\arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths'

**Comment by thstkdgus35** [comment]
Hello.

This issue is related to your python environment. Please make sure that your skimage package is installed well.

Thank you.
