### ISSUE TITLE
Pytorch loading problem

### ISSUE THREAD

**Issue by greatwallet** [thstkdgus35/EDSR-PyTorch#232]
Come across the same problem with #162 
# System
* Ubuntu 16.04 LTS
* CUDA Version: 10.1
* NVIDIA-SMI 430.40; Driver Version: 430.40
* Python: 3.6.9
* Pytorch 1.3.1
* Conda packages:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
blas                      1.0                         mkl    defaults
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.10.16                    0    defaults
cairo                     1.16.0            h18b612c_1001    conda-forge
certifi                   2019.9.11                py36_0    defaults
cffi                      1.13.2           py36h2e261b9_0    defaults
cloudpickle               1.2.2                      py_0    defaults
cudatoolkit               10.1.243             h6bb024c_0    defaults
cycler                    0.10.0                   py36_0    defaults
cytoolz                   0.10.1           py36h7b6447c_0    defaults
dask-core                 2.8.0                      py_0    defaults
dbus                      1.13.12              h746ee38_0    defaults
decorator                 4.4.1                      py_0    defaults
expat                     2.2.6                he6710b0_0    defaults
ffmpeg                    4.1.3                h167e202_0    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.9.1                h8a8886c_1    defaults
giflib                    5.1.9                h516909a_0    conda-forge
glib                      2.63.1               h5a9c865_0    defaults
gmp                       6.1.2             hf484d3e_1000    conda-forge
gnutls                    3.6.5             hd3a4fd2_1002    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
harfbuzz                  2.4.0                h37c48d4_1    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
icu                       58.2                 h9c2bf20_1    defaults
imageio                   2.6.1                    py36_0    defaults
intel-openmp              2019.4                      243    defaults
jasper                    1.900.1           h07fcdf6_1006    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
kiwisolver                1.1.0            py36he6710b0_0    defaults
lame                      3.100             h14c3975_1001    conda-forge
libblas                   3.8.0                    14_mkl    conda-forge
libcblas                  3.8.0                    14_mkl    conda-forge
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0                    14_mkl    conda-forge
liblapacke                3.8.0                    14_mkl    conda-forge
libpng                    1.6.37               hbc83047_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.1.0                h2733197_0    defaults
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.0.2                h576950b_1    conda-forge
libxcb                    1.13                 h1bed415_1    defaults
libxml2                   2.9.9                hea5a465_1    defaults
matplotlib                3.1.1            py36h5429711_0    defaults
mkl                       2019.4                      243    defaults
mkl-service               2.3.0            py36he904b0f_0    defaults
mkl_fft                   1.0.15           py36ha843d7b_0    defaults
mkl_random                1.1.0            py36hd6b4f25_0    defaults
ncurses                   6.1                  he6710b0_1    defaults
nettle                    3.4.1             h1bed415_1002    conda-forge
networkx                  2.4                        py_0    defaults
ninja                     1.9.0            py36hfd86e86_0    defaults
numpy                     1.17.3           py36hd14ec0e_0    defaults
numpy-base                1.17.3           py36hde5b4d6_0    defaults
olefile                   0.46                     py36_0    defaults
opencv                    3.4.7            py36h8949d38_2    conda-forge
openh264                  1.8.0             hdbcaa40_1000    conda-forge
openssl                   1.1.1d               h7b6447c_3    defaults
pcre                      8.43                 he6710b0_0    defaults
pillow                    6.2.1            py36h34e0f95_0    defaults
pip                       19.3.1                   py36_0    defaults
pixman                    0.38.0            h516909a_1003    conda-forge
pycparser                 2.19                     py36_0    defaults
pyparsing                 2.4.5                      py_0    defaults
pyqt                      5.9.2            py36h05f1152_2    defaults
python                    3.6.9                h265db76_0    defaults
python-dateutil           2.8.1                      py_0    defaults
pytorch                   1.3.1           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
pytz                      2019.3                     py_0    defaults
pywavelets                1.1.1            py36h7b6447c_0    defaults
qt                        5.9.7                h5867ecd_1    defaults
readline                  7.0                  h7b6447c_5    defaults
scikit-image              0.15.0           py36he6710b0_0    defaults
scipy                     1.3.1            py36h7c811a0_0    defaults
setuptools                41.6.0                   py36_0    defaults
sip                       4.19.8           py36hf484d3e_0    defaults
six                       1.13.0                   py36_0    defaults
sqlite                    3.30.1               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
toolz                     0.10.0                     py_0    defaults
torchvision               0.4.2                py36_cu101    pytorch
tornado                   6.0.3            py36h7b6447c_0    defaults
tqdm                      4.38.0                     py_0    defaults
wheel                     0.33.6                   py36_0    defaults
x264                      1!152.20180806       h14c3975_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4                h14c3975_4    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.3.7                h0b5b093_0    defaults
```
# Error
```
$ sh TestRCAN_scripts.sh
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import data
  File "/home/chxt/script/RCAN/RCAN_TestCode/code/data/__init__.py", line 3, in <module>
    from dataloader import MSDataLoader
  File "/home/chxt/script/RCAN/RCAN_TestCode/code/dataloader.py", line 10, in <module>
    from torch._C import _set_worker_signal_handlers, _update_worker_pids, \
ImportError: cannot import name '_update_worker_pids'
```

I suppose maybe the code is not supportive Pytorch 1.3.0 and above.

Could you give me a hint about how to fix this?

**Comment by AbdulMoqeet** [comment]
RCAN uses old EDSR code. Please replace the `dataloader.py` with EDSR `dataloader.py` to fix this issue. 

I would suggest to use the EDSR code and run the RCAN model from it to resolve such bugs.
