### ISSUE TITLE
how to run the  demo? 

### ISSUE THREAD

**Issue by qunshanzhang** [thstkdgus35/EDSR-PyTorch#244]
I am trying to follow  your Quickstart (Demo). 

I tried different   examples  in demo.sh,   but having the same issue:
~/workplace/SAN/EDSR-PyTorch/src$ sh demo.sh 
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    main()
  File "main.py", line 22, in main
    loader = data.Data(args)
  File "/home/qz/workplace/SAN/EDSR-PyTorch/src/data/__init__.py", line 31, in __init__
    num_workers=args.n_threads,
  File "/home/qz/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "/home/qz/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

I downloaded  your model  (EDSR_x2.pt  EDSR_x3.pt  EDSR_x4.pt  MDSR.pt
 )and put into /workplace/SAN/EDSR-PyTorch/experiment/model

and  under folder "test" there is a file ~/workplace/SAN/EDSR-PyTorch/test/0853x4.png
So I think it is enough to run  it and see result.  Am I missing anything to see/test  your result ? 
Thanks

**Comment by DengkeDu** [comment]
Duplicated by [217](https://github.com/thstkdgus35/EDSR-PyTorch/issues/217)

**Comment by qunshanzhang** [comment]
yes, just the path issue. I will close this ticket.

**Comment by Tangjian2344** [comment]
> yes, just the path issue. I will close this ticket.

Can you tell me in detail where there is a problem with the path? thank you！
