### ISSUE TITLE
own dataset import_module error

### ISSUE THREAD

**Issue by KN23** [thstkdgus35/EDSR-PyTorch#249]
Hello. I create my own dataset. However, when running main.py, an error ocurred like following.
1664f100 is a name of my dataset. please help

`Traceback (most recent call last):
  File "main.py", line 33, in <module>
    main()
  File "main.py", line 22, in main
    loader = data.Data(args)
  File "/home/EDSR-PyTorch/src/data/__init__.py", line 23, in __init__
    m = import_module('data.' + module_name.lower())
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'data.1664f100'`

**Comment by vineetasingh** [comment]
@KN23 I am having the same issue. Could you resolve this error?
