### ISSUE TITLE
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 0 and 96 in dimension 2 at /pytorch/aten/src/TH/generic/THTensor.cpp: 711

### ISSUE THREAD

**Issue by RuyuXu2019** [thstkdgus35/EDSR-PyTorch#260]
Hello! How can I solve this problem? It occurs in trainer.py, line 42.
 for batch ,( lr, hr, _,) in enumerate(self.loader_train):

**Comment by RuyuXu2019** [comment]
Making model...
Preparing loss function:
1.000 * L1
[Epoch 1]       Learning rate: 1.00e-4
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    main()
  File "main.py", line 27, in main
    t.train()
  File "/home/aistudio/EDSR-PyTorch/src/trainer.py", line 42, in train
    for batch, (lr, hr, _,) in enumerate(self.loader_train):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 79, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 79, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 0 and 96 in dimension 2 at /pytorch/aten/src/TH/generic/THTensor.cpp:612

**Comment by dalveasy** [comment]
hi  have you solved the problem?
