### ISSUE TITLE
when I train the RDN ,list index out of range happens

### ISSUE THREAD

**Issue by countingstarsmer** [thstkdgus35/EDSR-PyTorch#270]
(EDSR) zhj@server1:~/EDSR/EDSR-PyTorch-legacy-1.0.0/src$ python3.6 main.py --scale 2 --save RDN_D16C8G64_BIx2 --model RDN --epochs 200 --batch_size 16 --data_range 801-805 --patch_size 64 --reset
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    main()
  File "main.py", line 22, in main
    loader = data.Data(args)
  File "/home/zhj/EDSR/EDSR-PyTorch-legacy-1.0.0/src/data/__init__.py", line 41, in __init__
    testset = getattr(m, module_name)(args, train=False, name=d)
  File "/home/zhj/EDSR/EDSR-PyTorch-legacy-1.0.0/src/data/div2k.py", line 13, in __init__
    data_range = data_range[1]
IndexError: list index out of range

**Comment by leoliu37** [comment]
@countingstarsmer I meet the same problem. I modify the 'data_range' setting or delete it , and it works.
