### ISSUE TITLE
helpValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by Hunter-Murphy** [thstkdgus35/EDSR-PyTorch#276]
when i used the “” to train the EDSR model from the scratch，i met the error ：
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    main()
  File "main.py", line 22, in main
    loader = data.Data(args)
  File "E:\红外成像仪\code\EDSR-PyTorch-master\src\data\__init__.py", line 34, in __init__
    num_workers=args.n_threads,
  File "C:\ProgramData\Anaconda3\envs\py37pt0.4.1\lib\site-packages\torch\utils\data\dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "C:\ProgramData\Anaconda3\envs\py37pt0.4.1\lib\site-packages\torch\utils\data\sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

what can i do to solve it ？i deed help,  thanks.

**Comment by JaChouSSS** [comment]
add the '--test_only' after your test commend

**Comment by JaChouSSS** [comment]
@Hunter-Murphy

**Comment by Hunter-Murphy** [comment]
thanks very very much！！but i still encounter some severe errors when i reimplement the source code of the EDSR using my own datasets，i want to ask you some questions，here is my email address（murphy.ai@qq.com）.May I ask your email addressl？thanks again

**Comment by Hunter-Murphy** [comment]
@JaChouSSS

**Comment by JaChouSSS** [comment]
hi，i am also reimplementing too&nbsp;
my email is 958086580@qq.com



---Original---

**Comment by JaChouSSS** [comment]
> @JaChouSSS

hi，my email is jaychou10261026@163.com

**Comment by yjt9299** [comment]
Did you solve the problem? How? Thank you i also meet this problem when i use the " python main.py --model EDSR --scale 2 --save edsr_x2 --n_resblocks 32 --n_feats 256 --res_scale 0.1 --reset --ext sep-reset  " to train the model

**Comment by yjt9299** [comment]
@Hunter-Murphy

**Comment by yjt9299** [comment]
> add the '--test_only' after your test commend

If i want train the model and i meet this error  how can i solve it ? Thank u

**Comment by yjt9299** [comment]
i get it  . i made a mistake on the dir_data

**Comment by Hunter-Murphy** [comment]
Not yet,i am still trying to solve it!
Cause im busy these days,but i will try to solve it again in the next few days. Just keep in touch!
thanks for you help!@yjt9299

**Comment by flag16** [comment]
> 在测试成绩后添加“ --test_onl

> Not yet,i am still trying to solve it!
> Cause im busy these days,but i will try to solve it again in the next few days. Just keep in touch!
> thanks for you help!@yjt9299
I have the same problem with you. 
If you have solved it please help me.
Thank you.  e-mail:954723924@qq.com

**Comment by flag16** [comment]
I have the same problem with you.
If you have solved the problem please help me.
Thanks.   e-mail:954723924@qq.com
@Hunter-Murphy

**Comment by qizhou000** [comment]
看这个邮箱好像都是中国老铁啊

**Comment by fac33** [comment]
@yjt9299  Not so sure if you can explain more on how you could solve the problem? It looks like I had encounter the same issue here and though I change my dir_data's default directory for several times it still not works. By the way you can contact me through cfy_98@126.com. Thanks again!

**Comment by WithWheat** [comment]
@fac33 @qizhou000 @Hunter-Murphy @flag16 
Hi, guys! Just change the 'dir_data' in 'option.py' correctly then this bug will be fixed.
For example, you can do it like this, '/home/aaa/bbb/DIV2K/'--->'/home/aaa/bbb/'
Hope this works.

**Comment by baba1587** [comment]
> @fac33 @qizhou000 @Hunter-Murphy @flag16
> Hi, guys! Just change the 'dir_data' in 'option.py' correctly then this bug will be fixed.
> For example, you can do it like this, '/home/aaa/bbb/DIV2K/'--->'/home/aaa/bbb/'
> Hope this works.

thank you for your help

**Comment by TiamoV58756565745345** [comment]
I have the same problem with you.
If you have solved the problem please help me.
Thanks. e-mail:[429688152@qq.com]
@Hunter-Murphy
