### ISSUE TITLE
How to train the model with the Adversarial Loss? 

### ISSUE THREAD

**Issue by jiandandan001** [thstkdgus35/EDSR-PyTorch#299]
Hi, how to train the model with the Adversarial Loss?
Could you give an example of the code? Thanks

**Comment by jiandandan001** [comment]
I have the following problem. Do you know the reason?  thanks
******************************************************
Preparing loss function:
Traceback (most recent call last):
  File "code/main.py", line 21, in <module>
    loss = loss.Loss(args, checkpoint) if not args.test_only else None
  File "/loss/__init__.py", line 36, in __init__
    module = import_module('loss.adversarial')
  File "anaconda3/envs/pytorch1.1python2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "loss/adversarial.py", line 85
    return dict(**state_discriminator, **state_optimizer)
                                     ^
SyntaxError: invalid syntax
