### ISSUE TITLE
怎么使用自定义的数据集训练？

### ISSUE THREAD

**Issue by Liiiiaictx** [thstkdgus35/EDSR-PyTorch#357]
我更改了和DIV2K一样的结构，出现以下这种错误：
(EDSR) root@autodl-container-6b4f11a552-34a21590:~/autodl-tmp/EDSR-PyTorch/src# python main.py --model EDSR --scale 2 --save edsr_x2 --n_resblocks 32 --n_feats 256 --res_scale 0.1 --reset 
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    main()
  File "main.py", line 22, in main
    loader = data.Data(args)
  File "/root/autodl-tmp/EDSR-PyTorch/src/data/__init__.py", line 23, in __init__
    m = import_module('data.' + module_name.lower())
  File "/root/miniconda3/envs/EDSR/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'data.aid'

我的新数据集的目录结构如下：
![22](https://github.com/sanghyun-son/EDSR-PyTorch/assets/151444958/519f68f7-6718-497e-b4b4-fb78438bf106)

**Comment by Sherlock-hh** [comment]
https://blog.csdn.net/qq_41890263/article/details/125790425

**Comment by cjzhzh** [comment]
我有个疑问啊 将epoch设置为300后 发现终端中只输出epoch1-299   究竟是运行了300epoch还是299epoch啊

**Comment by Liiiiaictx** [comment]
@cjzhzh 这个问题不大，你训练300轮用了多长时间啊

**Comment by cjzhzh** [comment]
我用的一篇基于EDSR的改进CARN 用的单卡4080 大概3个多小时

**Comment by Liiiiaictx** [comment]
@cjzhzh 你知道EDSR怎么添加SSIM的计算方法

**Comment by cjzhzh** [comment]
推理吗 还是训练？推理的话网上找一份算ssim的就行

**Comment by Liiiiaictx** [comment]
@cjzhzh EDSR训练的时候在验证阶段只计算了psnr,这个怎么添加SSIM计算。CARN有计算SSIM指标吗

**Comment by cjzhzh** [comment]
CARN在验证的时候也没有ssim的计算

**Comment by cjzhzh** [comment]
https://github.com/xindongzhang/ELAN
这个有

**Comment by Liiiiaictx** [comment]
@cjzhzh 好的感谢，兄弟加个好友讨论下呗qq:2814669702@qq.com

**Comment by lishaoru-dev** [comment]
目录结构如何设置的
