### ISSUE TITLE
NameError: free variable 'device' referenced before assignment in enclosing scope

### ISSUE THREAD

**Issue by ssstitch** [thstkdgus35/EDSR-PyTorch#360]

**Comment by ssstitch** [comment]
I run the main.py with
--data_test
Set5
--scale
4
--pre_train
/home/stitch/EDSR-PyTorch-master/experiment/test/model/EDSR_x4.pt
--test_only
--save_results

occered this error
Evaluation:
  0%|                                                     | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/stitch/EDSR-PyTorch-master/src/main.py", line 33, in <module>
    main()
  File "/home/stitch/EDSR-PyTorch-master/src/main.py", line 26, in main
    while not t.terminate():
  File "/home/stitch/EDSR-PyTorch-master/src/trainer.py", line 147, in terminate
    self.test()
  File "/home/stitch/EDSR-PyTorch-master/src/trainer.py", line 90, in test
    lr, hr = self.prepare(lr, hr)
  File "/home/stitch/EDSR-PyTorch-master/src/trainer.py", line 143, in prepare
    return [_prepare(a) for a in args]
  File "/home/stitch/EDSR-PyTorch-master/src/trainer.py", line 143, in <listcomp>
    return [_prepare(a) for a in args]
  File "/home/stitch/EDSR-PyTorch-master/src/trainer.py", line 141, in _prepare
    return tensor.to(device)
NameError: free variable 'device' referenced before assignment in enclosing scope

what should I do,thanks
