### ISSUE TITLE
Question about training on new dataset

### ISSUE THREAD

**Issue by drStacky** [thstkdgus35/EDSR-PyTorch#51]
How can I train EDSR on my own (non-standard) dataset? Is there a straightforward way to do this with the current code? I'd also like to explore transfer learning with one of the pre-trained models if possible.

**Comment by thstkdgus35** [comment]
Hello.

Defining a new dataset is very simple.

Just copy the ``code/data/div2k.py`` and rename it as you want (**USE LOWER CASES ONLY**).

Then, set the class name (**If your class name is 'Custom', then your file name should be 'custom.' See [these lines](https://github.com/thstkdgus35/EDSR-PyTorch/blob/02a3fba34ec1d8335de259ca874405f9cff077b5/code/data/__init__.py#L10-L11)) and modify [some lines about directory structures](https://github.com/thstkdgus35/EDSR-PyTorch/blob/02a3fba34ec1d8335de259ca874405f9cff077b5/code/data/div2k.py#L17-L20).

Since the ``div2k.py`` file is very simple, I think you can make your own class easily.

Please let me know if you have any questions.

Thank you.

**Comment by drStacky** [comment]
Thank you for your quick response.

I made the modifications you suggested. I can get the it to start training, but it fails during the testing stage.
```
Traceback (most recent call last):
  File "EDSR-PyTorch/code/main.py", line 20, in <module>
    t.test()
  File "/mnt/tier2/mstackpo/EDSR-PyTorch/code/trainer.py", line 110, in test
    self.ckp.log[-1, idx_scale] = eval_acc / len(self.loader_test)
ZeroDivisionError: division by zero
```
This makes it seem like it has no test set. However, I used `--data_train MyDataDir --data_test MyDataDir --data_range 1-90/91-100` to split my 100 images into 90 for training and 10 for testing (or so I thought). Is there something else I need to do to specify a test set?

On a related note, the portion I got working was because I converted my images to PNG format. Ultimately, I'd like to work with TIFFs. I've tried using `--ext tif`, and even went so far as to change [this line](https://github.com/thstkdgus35/EDSR-PyTorch/blob/02a3fba34ec1d8335de259ca874405f9cff077b5/code/data/srdata.py#L109) to `self.ext = ('.tif', '.tif')`, but neither worked.

I appreciate your help very much.

**Comment by drStacky** [comment]
It looks like it built the binaries for the first 1-90 images, but I can't find any for 91-100. When I try training DIV2K, I see binaries for all 810 images (800 training and 10 test).

**Comment by thstkdgus35** [comment]
Hello.

``--ext tif`` is an invalid command.

maybe you have to carefully redefine the ``_set_filesystem`` function to avoid the happening.

Or, please share your code to me so that I can give a help.

Thank you.

**Comment by kikiki1121** [comment]
Excuse me.
Mr.drStacky.
I am also planning to train with my data set.
Could you please show me the source code you changed?

**Comment by Shawf** [comment]
@thstkdgus35 ，can you tell me which function return the ‘idx_scale’ in “for batch, (lr, hr, _, idx_scale) in enumerate(self.loader_train)”，in train.py . thanks

**Comment by XuecaiHu** [comment]
> @thstkdgus35 ，can you tell me which function return the ‘idx_scale’ in “for batch, (lr, hr, _, idx_scale) in enumerate(self.loader_train)”，in train.py . thanks

in the dataloader.py: def _ms_loop function--> samples.append(idx_scale)

**Comment by Akshaypatil7** [comment]
@kikiki1121  did you got the source code, i am facing same problem

**Comment by bostankhan6** [comment]
@sanghyun-son 
I am following the same steps as you described but I am getting the following error:
**Traceback (most recent call last):
  File "/content/EDSR-PyTorch/src/main.py", line 33, in <module>
    main()
  File "/content/EDSR-PyTorch/src/main.py", line 22, in main
    loader = data.Data(args)
  File "/content/EDSR-PyTorch/src/data/__init__.py", line 24, in __init__
    datasets.append(getattr(m, module_name)(args, name=d))
  File "/content/EDSR-PyTorch/src/data/simd.py", line 17, in __init__
    args, name=name, train=train, benchmark=benchmark
  File "/content/EDSR-PyTorch/src/data/srdata.py", line 61, in __init__
    n_images = len(args.data_train) * len(self.images_hr)
AttributeError: 'SIMD' object has no attribute 'images_hr'**

I am getting the above error for the following command:
**python /content/EDSR-PyTorch/src/main.py --model EDSR --scale 4 --save edsr_baseline_x4 --dir_data /content/simd --reset --ext jpeg --data_train SIMD --pre_train /content/EDSR-PyTorch/experiment/model**

**Comment by lidanyang916** [comment]
I have the same problem, have you saved it? 

> @sanghyun-son
> I am following the same steps as you described but I am getting the following error:
> **Traceback (most recent call last): File "/content/EDSR-PyTorch/src/main.py", line 33, in main() File "/content/EDSR-PyTorch/src/main.py", line 22, in main loader = data.Data(args) File "/content/EDSR-PyTorch/src/data/**init**.py", line 24, in **init** datasets.append(getattr(m, module_name)(args, name=d)) File "/content/EDSR-PyTorch/src/data/simd.py", line 17, in **init** args, name=name, train=train, benchmark=benchmark File "/content/EDSR-PyTorch/src/data/srdata.py", line 61, in **init** n_images = len(args.data_train) * len(self.images_hr) AttributeError: 'SIMD' object has no attribute 'images_hr'**
> 
> I am getting the above error for the following command:
> **python /content/EDSR-PyTorch/src/main.py --model EDSR --scale 4 --save edsr_baseline_x4 --dir_data /content/simd --reset --ext jpeg --data_train SIMD --pre_train /content/EDSR-PyTorch/experiment/model**

I have the same problem, have you saved it?

**Comment by Liiiiaictx** [comment]
@lidanyang916 你知道怎么用自己数据集训练？
