### ISSUE TITLE
Final model loading

### ISSUE THREAD

**Issue by cfrancesco** [thstkdgus35/EDSR-PyTorch#62]
I downloaded the final models from here:
https://cv.snu.ac.kr/research/EDSR/model_pytorch.tar

I am running a test with the following command:

`python main.py --data_test Demo --scale 3 --pre_train ../experiment/model/EDSR_x3.pt --test_only --save_results --cpu`

And I get the output:

> Making model...
> Loading model from ../experiment/model/EDSR_x3.pt
> Traceback (most recent call last):
>   File "***/EDSR-PyTorch/src/model/edsr.py", line 71, in load_state_dict
>     own_state[name].copy_(param)
> RuntimeError: The expanded size of the tensor (64) must match the existing size (256) at non-singleton dimension 0
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "main.py", line 15, in <module>
>     model = model.Model(args, checkpoint)
>   File "***/EDSR-PyTorch/src/model/__init__.py", line 34, in __init__
>     cpu=args.cpu
>   File "***/EDSR-PyTorch/src/model/__init__.py", line 103, in load
>     strict=False
>   File "***/EDSR-PyTorch/src/model/edsr.py", line 77, in load_state_dict
>     .format(name, own_state[name].size(), param.size()))
> RuntimeError: While copying the parameter named head.0.weight, whose dimensions in the model are torch.Size([64, 3, 3, 3]) and whose dimensions in the checkpoint are torch.Size([256, 3, 3, 3]).
> 

Everything works fine when using the baseline models with:
`python main.py --data_test Demo --scale 3 --pre_train ../experiment/model/EDSR_baseline_x3.pt --test_only --save_results --cpu`

**Comment by cfrancesco** [comment]
Taken from another answer:
`python main.py --data_test Demo --scale 2 --n_resblocks 32 --n_feats 256 --res_scale 0.1 --pre_train ../experiment/model/EDSR_x2.pt --test_only --save_results --cpu`

Maybe add a note on the readme?
