### ISSUE TITLE
Got suspicious insufficient shared memory issue when Evaluation

### ISSUE THREAD

**Issue by elvis1423** [thstkdgus35/EDSR-PyTorch#83]
Dear author,
I'm trying to train a EDSR_X2 model using DIV2K 1-80 images on Nvidia Tesla P100 GPU which has 16G memory.
I used this command:
python main.py --model EDSR --scale 2 --save EDSR_x2 --n_resblocks 32 --n_feats 256 --res_scale 0.1 --reset
But get below error when evaluating after epoch 1:
Making model...
Preparing loss function:
1.000 * L1
[Epoch 1]	Learning rate: 1.00e-4
[800/8000]	[L1: 9.6905]	166.2+4.7s
[1600/8000]	[L1: 7.7327]	166.2+4.6s
[2400/8000]	[L1: 6.9817]	166.2+4.6s
[3200/8000]	[L1: 6.5375]	166.2+4.6s
[4000/8000]	[L1: 6.2981]	166.2+4.6s
[4800/8000]	[L1: 6.1586]	166.2+4.6s
[5600/8000]	[L1: 6.0399]	166.2+4.6s
[6400/8000]	[L1: 5.9229]	166.2+4.6s
[7200/8000]	[L1: 5.8188]	166.2+4.6s
[8000/8000]	[L1: 5.7089]	166.2+4.6s

Evaluation:
  0%|                                                    | 0/10 [00:00<?, ?it/s]ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    t.test()
  File "/notebooks/ai/EDSR-PyTorch-master/src/trainer.py", line 88, in test
    for idx_img, (lr, hr, filename, _) in enumerate(tqdm_test):
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py", line 979, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 330, in __next__
    idx, batch = self._get_batch()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 309, in _get_batch
    return self.data_queue.get()
  File "/usr/lib/python3.6/queue.py", line 164, in get
    self.not_empty.wait()
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 227, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 6915) is killed by signal: Bus error. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.
Could you please give some advises?
Thanks.

**Comment by thstkdgus35** [comment]
Hello.

How much RAM do you have?

Please try with ``--n_threads 0`` and let me know if it works.

Thank you!

**Comment by elvis1423** [comment]
Hi, 
I have 16G GPU RAM, and tried --n_threads 0, now it throws unpack error:
Making model...
Preparing loss function:
1.000 * L1
[Epoch 1]	Learning rate: 1.00e-4
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    t.train()
  File "/notebooks/ai/EDSR-PyTorch-master/src/trainer.py", line 45, in train
    for batch, (lr, hr, _, idx_scale) in enumerate(self.loader_train):
ValueError: not enough values to unpack (expected 4, got 3)

I also tried --n_threads 1, it threw insufficient shared memory error when Evaluation again.
Any further suggestions to try?

**Comment by elvis1423** [comment]
Thanks for the suggestion, and the insufficient shared memory issue has gone.

**Comment by dongxijia** [comment]
Hello, I got same error , and I try same way as you did. But new error arise:
when replace
`for batch, (lr, hr, _, idx_scale) in enumerate(self.loader_train):` to
`for batch, (lr, hr, _) in enumerate(self.loader_train):`
then rise "NameError: name 'idx_scale' is not defined" in line 52
`sr = self.model(lr, idx_scale)`
Thank you for your help.

**Comment by elvis1423** [comment]
Hi, I walked around the error by defining idx_scale=xxx in a new line, hope will help you.
