### ISSUE TITLE
error inwindows

### ISSUE THREAD

**Issue by taniaCHY** [thstkdgus35/EDSR-PyTorch#88]
Making model...
Preparing loss function:
1.000 * L1
[Epoch 1]       Learning rate: 1.00e-4
Making model...
Preparing loss function:
1.000 * L1
[Epoch 1]       Learning rate: 1.00e-4
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "main.py", line 25, in <module>
  File "C:\Users\13265\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    t.train()
  File "D:\Piao_Yi_Is_File\EDSR-PyTorch-master\src\trainer.py", line 41, in train
    exitcode = _main(fd)
  File "C:\Users\13265\Anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
        for batch, (lr, hr, _, idx_scale) in enumerate(self.loader_train):prepare(preparation_data)

  File "D:\Piao_Yi_Is_File\EDSR-PyTorch-master\src\dataloader.py", line 144, in __iter__
  File "C:\Users\13265\Anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\13265\Anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\13265\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\13265\Anaconda3\lib\runpy.py", line 96, in _run_module_code
        return _MSDataLoaderIter(self)mod_name, mod_spec, pkg_name, script_name)

  File "C:\Users\13265\Anaconda3\lib\runpy.py", line 85, in _run_code
  File "D:\Piao_Yi_Is_File\EDSR-PyTorch-master\src\dataloader.py", line 117, in __init__
        exec(code, run_globals)w.start()

  File "D:\Piao_Yi_Is_File\EDSR-PyTorch-master\src\main.py", line 25, in <module>
  File "C:\Users\13265\Anaconda3\lib\multiprocessing\process.py", line 105, in start
        t.train()self._popen = self._Popen(self)

  File "D:\Piao_Yi_Is_File\EDSR-PyTorch-master\src\trainer.py", line 41, in train
  File "C:\Users\13265\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
        for batch, (lr, hr, _, idx_scale) in enumerate(self.loader_train):return _default_context.get_context().Process._Popen(process_obj)

  File "D:\Piao_Yi_Is_File\EDSR-PyTorch-master\src\dataloader.py", line 144, in __iter__
  File "C:\Users\13265\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return _MSDataLoaderIter(self)
return Popen(process_obj)  File "D:\Piao_Yi_Is_File\EDSR-PyTorch-master\src\dataloader.py", line 117, in __init__

      File "C:\Users\13265\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
w.start()
reduction.dump(process_obj, to_child)  File "C:\Users\13265\Anaconda3\lib\multiprocessing\process.py", line 105, in start

      File "C:\Users\13265\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
self._popen = self._Popen(self)
ForkingPickler(file, protocol).dump(obj)  File "C:\Users\13265\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen

    BrokenPipeErrorreturn _default_context.get_context().Process._Popen(process_obj):
[Errno 32] Broken pipe  File "C:\Users\13265\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen

    return Popen(process_obj)
  File "C:\Users\13265\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\13265\Anaconda3\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\13265\Anaconda3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
^C

**Comment by tabetomo** [comment]
It seems it is a duplicated issue in #91.
